name: Build-Deploy

on:
  push:
    branches: [main]

jobs:
  use-build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: use-build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: build

      - name: Set up node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Deploy project
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
